DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS COMMENTS;

CREATE TABLE AUTHORS(
                        ID BIGINT AUTO_INCREMENT PRIMARY KEY,
                        FIRSTNAME VARCHAR(255),
                        LASTNAME VARCHAR(255)
);
CREATE TABLE GENRES(
                       ID BIGINT AUTO_INCREMENT PRIMARY KEY,
                       NAME VARCHAR(255)
);

CREATE TABLE BOOKS(
                      ID BIGINT AUTO_INCREMENT PRIMARY KEY,
                      NAME VARCHAR(255),
                      AUTHOR_ID BIGINT NOT NULL,
                      FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(ID) ON DELETE CASCADE,
                      GENRE_ID BIGINT NOT NULL,
                      FOREIGN KEY (GENRE_ID) REFERENCES GENRES(ID) ON DELETE CASCADE
);
CREATE TABLE COMMENTS(
                         ID BIGINT AUTO_INCREMENT PRIMARY KEY,
                         COMMENT_TEXT VARCHAR(255),
                         BOOK_ID BIGINT NOT NULL,
                         FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(ID) ON DELETE CASCADE
);